### ISSUE TITLE
Grouping_legend_mapping权重文件

### ISSUE THREAD

**Issue by limaopeng1** [Shiva-sankaran/LineEX#5] opened 2023-07-12 12:30 UTC
你好，请问可以提供modules/Grouping_legend_mapping/ckpts/mlp_ckpt.t7、modules/Grouping_legend_mapping/ckpts/ckpt_30.t7两个权重文件吗，感谢

**Comment by Shiva-sankaran** [comment] 2023-07-13 06:34
Duplicate of https://github.com/Shiva-sankaran/LineEX/issues/6

**Closed as completed by Shiva-sankaran** 2023-07-13 06:34 UTC
